# Generated by Django 4.1.7 on 2023-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(null=True, upload_to="files/"),
        ),
    ]
